language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails_master.gemfile

matrix:
  include:
    - rvm: 2.3.6
      gemfile: gemfiles/rails3.2.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
  fast_finish: true

notifications:
  email:
    - daniel.r.whalen+travis-ci@gmail.com
