language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.8
  - 2.3.5

gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

matrix:
  include:
    - rvm: 2.1.10
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails5.1.gemfile
  fast_finish: true

notifications:
  email:
    - daniel.r.whalen+travis-ci@gmail.com
