language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
gemfile:
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.0.gemfile
    - rvm: jruby-head
notifications:
  email:
    - daniel.r.whalen+travis-ci@gmail.com
